# Root

#
# 15 minutes countdown
#
[[items]]
name = "start_15m"
path = "start_button.py"
type = "button"

[items.params]
duration = 900
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5

#
# 30 minutes countdown
#
[[items]]
name = "start_30m"
path = "start_button.py"
type = "button"

[items.params]
duration = 1800
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5

#
# 5 minutes countdown
#
[[items]]
name = "start_5m"
path = "start_button.py"
type = "button"

[items.params]
duration = 10
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5

#
# 40 minutes countdown
#
[[items]]
name = "start_40m"
path = "start_button.py"
type = "button"

[items.params]
duration = 2400
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5

#
# Pause button
#
[[items]]
name = "pause"
path = "start_button.py"
type = "button"

[items.params]
action = "pause"
font_family = "Roboto-Bold"
font_size = 270
font_color = "white"
icon_inactive = "countdown_pause"
icon_pressed = "countdown_pause_pressed"
icon_current = ""
icon_next = ""
icon_current_next = ""
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0

#
#
# Countdown display
#
#
[[items]]
name = "countdown_hour"
path = "count_down.py"
type = "button"

[items.params]
mode = "hours"
font_family = "Pixel LCD-7"
font_size = 200
icon_y_offset = 0
alarm_mode_time = 11

[[items]]
name = "countdown_minute"
path = "count_down.py"
type = "button"

[items.params]
mode = "minutes"
font_family = "Pixel LCD-7"
font_size = 200
icon_y_offset = 0
alarm_mode_time = 11

[[items]]
name = "countdown_second"
path = "count_down.py"
type = "button"

[items.params]
mode = "seconds"
font_family = "Pixel LCD-7"
font_size = 200
icon_y_offset = 0
alarm_mode_time = 11

#
# Stop button
#
[[items]]
name = "stop"
path = "start_button.py"
type = "button"

[items.params]
action = "stop"
font_family = "Roboto-Bold"
font_size = 270
font_color = "white"
icon_inactive = "countdown_stop"
icon_pressed = "countdown_stop_pressed"
icon_current = ""
icon_next = ""
icon_current_next = ""
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0

#
# 1 hour countdown
#
[[items]]
name = "start_1h"
path = "start_button.py"
type = "button"

[items.params]
duration = 3600
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5

#
# Clock display
#
[[items]]
name = "clock_hours"
path = "time_clock.py"
type = "button"

[items.params]
mode = "hours"
font_family = "Pixel LCD-7"
font_size = 200

[[items]]
name = "clock_minutes"
path = "time_clock.py"
type = "button"

[items.params]
mode = "minutes"
font_family = "Pixel LCD-7"
font_size = 200

[[items]]
name = "clock_seconds"
path = "time_clock.py"
type = "button"

[items.params]
mode = "seconds"
font_family = "Pixel LCD-7"
font_size = 200

#
# 2 hours countdown
#
[[items]]
name = "start_2h"
path = "start_button.py"
type = "button"

[items.params]
duration = 7200
action = "start"
font_family = "Roboto-Bold"
font_size = 120
font_color = "white"
icon_inactive = "countdown"
icon_pressed = "countdown_pressed"
icon_current = "countdown_current"
icon_next = "countdown_next"
icon_current_next = "countdown_current_next"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
icon_y_offset = -5
